import { MainChar } from './base/MainChar.js';

var isaac= new MainChar(
    "isaac",
    actions,
    index,
    walk_speed,
    dash_speed,
    climb_speed,
    push_speed,
    avatar_image_path,
    name,
    hp_curve,
    pp_curve,
    atk_curve,
    def_curve,
    agi_curve,
    luk_curve,
    exp_curve,
    starting_level,
    venus_level_base,
    mercury_level_base,
    mars_level_base,
    jupiter_level_base,
    venus_power_base,
    mercury_power_base,
    mars_power_base,
    jupiter_power_base,
    venus_resist_base,
    mercury_resist_base,
    mars_resist_base,
    jupiter_resist_base,
    innate_abilities,
    in_party,
    djinni
);
